### ISSUE TITLE
aXMLRPC

### ISSUE THREAD

**Issue by makoysof** [gturri/aXMLRPC#113]
Hi. I'm trying to use axmlrpc to connect to odoo in android studio. When I try to create a record, this error is shown.

W/System.err: de.timroes.axmlrpc.XMLRPCServerException: Traceback (most recent call last):
      File "/opt/odoo13/odoo13-server/odoo/addons/base/controllers/rpc.py", line 63, in xmlrpc_2
        response = self._xmlrpc(service)
      File "/opt/odoo13/odoo13-server/odoo/addons/base/controllers/rpc.py", line 43, in _xmlrpc
        result = dispatch_rpc(service, method, params)
      File "/opt/odoo13/odoo13-server/odoo/http.py", line 138, in dispatch_rpc
        result = dispatch(method, params)
      File "/opt/odoo13/odoo13-server/odoo/service/model.py", line 25, in dispatch
        (db, uid, passwd ) = params[0], int(params[1]), params[2]
    ValueError: invalid literal for int() with base 10: 'admin'
     [1]
W/System.err:     at de.timroes.axmlrpc.ResponseParser.parse(ResponseParser.java:78)
        at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:747)
        at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:467)
        at com.mark.busworld.Odoo.createPartner(Odoo.java:53)
        at com.mark.busworld.SignUp$2$1.run(SignUp.java:367)
        at java.lang.Thread.run(Thread.java:919)

**Comment by gturri** [comment]
Hi,
The error is occuring on the server side so you should probably get in touch with odoo instead of axmlrpc.
That being said, you might want to have a look at the [debug flag](https://github.com/gturri/aXMLRPC#flags_debug): it should give you more clue about what is occuring.
