### ISSUE TITLE
aXMLRPC

### ISSUE THREAD

**Issue by makoysof** [gturri/aXMLRPC#114]
Hi. So I'm using axmlrpc to connect android to odoo. When trying to create a model, I encounter this error.

de.timroes.axmlrpc.XMLRPCException: No serializer found for type 'com.mark.busworld.DatabaseHandler'.
        at de.timroes.axmlrpc.serializer.SerializerHandler.serialize(SerializerHandler.java:193)
W/System.err:     at de.timroes.axmlrpc.Call.getXMLParam(Call.java:91)
        at de.timroes.axmlrpc.Call.getXML(Call.java:67)
        at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:664)
        at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:467)
W/System.err:     at com.mark.busworld.SignUp$2$1.run(SignUp.java:372)
        at java.lang.Thread.run(Thread.java:919)

Do you have any idea on how to fix this?

**Comment by gturri** [comment]
Hi,
This error means that the response from the server is incorrect. In order to know more about what is going on you should try using the [debug flag](https://github.com/gturri/aXMLRPC#flags_debug)
