### ISSUE TITLE
How to determine which params that couldn't be serialized? NullPointerException

### ISSUE THREAD

**Issue by adadion** [gturri/aXMLRPC#68]
Hello, I had method call that couldnt be serialized. So it gives me NullPointerException. I've already giving FLAGS_NIL to send null params.

I've succesfully execute create method call, with the exact same params.
In update method, the params is exactly the same, plus an id as java List as the conditions.

I've debug it, and it has correct data to be sent.
But when it comes to call update method, it gives me NPE.

Is there any way I could determine which data that can't be serialize so I could get find another way?

My logcat 
`E/AndroidRuntime: FATAL EXCEPTION: Thread-1039
                  Process: com.ati.opentoko, PID: 12110
                  java.lang.NullPointerException
                      at de.timroes.axmlrpc.serializer.SerializerHandler.serialize(SerializerHandler.java:221)
                      at de.timroes.axmlrpc.serializer.StructSerializer.serialize(StructSerializer.java:99)
                      at de.timroes.axmlrpc.serializer.SerializerHandler.serialize(SerializerHandler.java:224)
                      at de.timroes.axmlrpc.Call.getXMLParam(Call.java:88)
                      at de.timroes.axmlrpc.Call.getXML(Call.java:64)
                      at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:659)
                      at de.timroes.axmlrpc.XMLRPCClient$Caller.run(XMLRPCClient.java:587)`

My code
`private void updateSOToOdoo() {

        List ids = Arrays.asList(saleOrder.getId());
        Map<String,Object> data = new HashMap<>();
        data.put("doc_date", saleOrder.getDocDate());
        data.put("required_date", saleOrder.getRequiredDate());
        data.put("shop_id", saleOrder.getShopId());
        data.put("salesman_id", saleOrder.getSalesmanId());
        data.put("next", saleOrder.getNext());
        data.put("is_partner", saleOrder.getIsPartner());
        data.put("customer_id", saleOrder.getCustomerId());
        data.put("address_id", saleOrder.getAddressId());
        data.put("customer_name", saleOrder.getCustomerName());
        data.put("customer_address", saleOrder.getCustomerAddress());
        data.put("customer_phone", saleOrder.getCustomerPhone());
        data.put("use_vat", saleOrder.getUseVat());
        data.put("po_ref", saleOrder.getPoRef());
        data.put("po_date", saleOrder.getPoDate());
        data.put("amount", saleOrder.getAmount());
        data.put("ppn_amount", saleOrder.getPpnAmount());
        data.put("sale_amount", saleOrder.getSaleAmount());
        data.put("cash_discount", saleOrder.getCashDiscount());
        data.put("total", saleOrder.getTotal());
        // on below gives me error
        updateSaleOrderTaskId = util.update(listener, database, uid, password, "sale.order", ids, data);
    }`

While this ones works
`private void updateSOLineToOdoo()  {

        List ids = Arrays.asList(saleOrderLine.getId());
        Map<String,Object> data = new HashMap<>();
        data.put("sale_id", saleOrderLine.getSale_id());
        data.put("product_id", saleOrderLine.getProduct_id());
        data.put("promo_id", saleOrderLine.getPromo_id());
        data.put("promo_type", saleOrderLine.getPromo_type());
        data.put("ppn_rate", saleOrderLine.getPpn_rate());
        data.put("qty", saleOrderLine.getQty());
        data.put("qty_carried", saleOrderLine.getQty_carried());
        data.put("qty_deliver", saleOrderLine.getQty_deliver());
        data.put("drate1", saleOrderLine.getDrate1());
        data.put("drate2", saleOrderLine.getDrate2());
        data.put("drate3", saleOrderLine.getDrate3());
        data.put("drate4", saleOrderLine.getDrate4());
        data.put("dratex", saleOrderLine.getDratex());
        data.put("price", saleOrderLine.getPrice());
        data.put("discount", saleOrderLine.getDiscount());
        data.put("amount", saleOrderLine.getAmount());
        data.put("ppn_amount", saleOrderLine.getPpn_amount());
        data.put("sale_amount", saleOrderLine.getSale_amount());
        updateSOLineTaskId = util.update(listener, database, uid, password, "sale.order.line", ids, data);
    }`

`private void createSOToOdoo() {

        Map<String,Object> data = new HashMap<>();
        data.put("doc_date", saleOrder.getDocDate());
        data.put("required_date", saleOrder.getRequiredDate());
        data.put("shop_id", saleOrder.getShopId());
        data.put("salesman_id", saleOrder.getSalesmanId());
        data.put("next", saleOrder.getNext());
        data.put("is_partner", saleOrder.getIsPartner());
        data.put("customer_id", saleOrder.getCustomerId());
        data.put("address_id", saleOrder.getAddressId());
        data.put("customer_name", saleOrder.getCustomerName());
        data.put("customer_address", saleOrder.getCustomerAddress());
        data.put("customer_phone", saleOrder.getCustomerPhone());
        data.put("use_vat", saleOrder.getUseVat());
        data.put("po_ref", saleOrder.getPoRef());
        data.put("po_date", saleOrder.getPoDate());
        data.put("cash_discount", saleOrder.getCashDiscount());
        createSOTaskId = util.create(listener, database, uid, password, "sale.order", data);
    }`

This is my helper class
`public class UtilAsync  {

    private URL url;
    private XMLRPCClient client;
    /*
    Constructor class to set server address and path
    path used for OpenERP object path, like common for login or authenticate, object for other call, like
    read, search, etc
    */
    UtilAsync(String serverAddress, String path) {
        try{
            url = new URL(serverAddress + "/xmlrpc/" + path);
            client = new XMLRPCClient(url, XMLRPCClient.FLAGS_NIL | XMLRPCClient.FLAGS_DEBUG);
        } catch(Exception ex) {
            Log.e("ODOO UTILITY: ", ex.getMessage());
        }
    }
    // asynchronous login method
    public long login(XMLRPCCallback listener, String db, String username, String password) {
        Map<String,Object> emptyMap = new HashMap<String,Object>();
        long id = client.callAsync(listener, "authenticate", db, username, password, emptyMap);
        return id;
    }

    // asynchronous search method
    public long search(XMLRPCCallback listener, String db, String uid, String password, String object, List conditions) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object, "search", conditions);
        return id;
    }

    // asynchronous read method
    public long read(XMLRPCCallback listener, String db, String uid, String password, String object, List conditions, List fields) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object, "read", conditions, fields);
        return id;
    }

    // asynchronous search and read method
    public long search_read(XMLRPCCallback listener, String db, String uid, String password, String object,
                            List conditions, Map<String, List>  fields ) {
        long id = client.callAsync(listener, "execute_kw", db, Integer.parseInt(uid), password, object,
                "search_read", conditions, fields);
        return id;
    }

    // asynchronous create method
    public long create(XMLRPCCallback listener, String db, String uid, String password, String object,
                       Map<String, ?> data) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "create", data);
        return id;
    }

    // asynchronous update method
    public long update(XMLRPCCallback listener, String db, String uid, String password, String object,
                       List ids, Map<String, ?> data){
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "write", ids, data);
        return id;
    }

    // asynchronous delete method
    public long delete(XMLRPCCallback listener, String db, String uid, String password, String object,
                       List ids) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "unlink", ids);
        return id;
    }

    // asynchronous send request to exec public method
    public long exec(XMLRPCCallback listener, String db, String uid, String password, String object,
                     String method, List data) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                method, data);
        return id;
    }

    // asynchronous approve object method
    public long do_approve(XMLRPCCallback listener, String db, String uid, String password, String object,
                           List ids) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object, "do_approve",
                ids);
        return id;
    }

    // asynchronous check salesman or not method
    public long member_of(XMLRPCCallback listener, String db, String uid, String password, String object,
                          String module, String group) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "member_of", module, group);
        return id;
    }

    // asynchronous check allowed shops for salesman method
    public long soe_salesman_shops(XMLRPCCallback listener, String db, String uid, String password,
                                   String object, String employeeId) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "soe_salesman_shops", Integer.parseInt(employeeId));
        return id;
    }

    // asynchronous check customer data method
    public long soe_customer_searchby(XMLRPCCallback listener, String db, String uid, String password,
                                      String object, String keyword) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "soe_customer_searchby", keyword);
        return id;
    }

    // asynchronous check customer address data method
    public long soe_customer_address(XMLRPCCallback listener, String db, String uid, String password,
                                      String object, String customerId) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "soe_customer_address", Integer.parseInt(customerId));
        return id;
    }

    // asynchronous check customer data by customerId method
    public long soe_customer_by_id(XMLRPCCallback listener, String db, String uid, String password,
                                      String object, String customerId) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "soe_customer_by_id", Integer.parseInt(customerId));
        return id;
    }

    // asynchronous check customer address data by addressId method
    public long soe_address_by_id(XMLRPCCallback listener, String db, String uid, String password,
                                     String object, String addressId) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "soe_address_by_id", Integer.parseInt(addressId));
        return id;
    }

    // asynchronous check product data method
    public long soe_product_searchby(XMLRPCCallback listener, String db, String uid, String password,
                                     String object, String keyword) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "soe_product_searchby", keyword);
        return id;
    }

    // asynchronous check product data by productId method
    public long soe_product_by_id(XMLRPCCallback listener, String db, String uid, String password,
                                     String object, String productId) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "soe_product_by_id", Integer.parseInt(productId));
        return id;
    }

    // asynchronous check product prices data method
    public long soe_product_prices(XMLRPCCallback listener, String db, String uid, String password,
                                   String object, String productId, String qty, String customerId,
                                   String useVat) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "soe_product_prices", Integer.parseInt(productId), Double.parseDouble(qty),
                Integer.parseInt(customerId), useVat);
        return id;
    }

    // asynchronous check product stock method
    public long soe_stock_current(XMLRPCCallback listener, String db, String uid, String password,
                                  String object, String productId) {
        long id = client.callAsync(listener, "execute", db, Integer.parseInt(uid), password, object,
                "soe_stock_current", Integer.parseInt(productId));
        return id;
    }

    // method to get ManyToOne field type
    public static M2OField getMany2One(Map<String,Object> classObj, String fieldName) {
        Integer fieldId = 0;
        String fieldValue="";
        M2OField res = new M2OField();
        if(classObj.get(fieldName) instanceof Object[]){
            Object[] field = (Object[])classObj.get(fieldName);
            if(field.length >0 ){
                fieldId = (Integer)field[0];
                fieldValue = (String)field[1];
            }
        }
        res.id = fieldId;
        res.value = fieldValue;

        return res;
    }

    // method to get OneToMany field type
    public static List getOne2Many(Map<String,Object> classObj, String fieldName) {
        List res = new ArrayList();
        Object[] field = (Object[])classObj.get(fieldName);

        for (int i=0; i<field.length; i++){
            res.add(i,  field[i]);
        }
        return res;
    }

    // method to get String value from field, if empty, return empty string ""
    public static String getString(Map<String,Object> classObj, String fieldName) {
        String res = "";
        if (classObj.get(fieldName) instanceof String){
            res = (String)classObj.get(fieldName);
        }
        return res;
    }

    // method to get Double value from field, if empty, return 0.0
    public static Double getDouble(Map<String,Object> classObj, String fieldName) {
        Double res = 0.0;
        if (classObj.get(fieldName) instanceof Double){
            res = (Double)classObj.get(fieldName);
        }
        return res;
    }

    // method to get Integer value from field, if empty, return 0
    public static Integer getInteger(Map<String,Object> classObj, String fieldName) {
        Integer res = 0;
        if (classObj.get(fieldName) instanceof Double){
            res = (Integer)classObj.get(fieldName);
        }
        return res;
    }

    // method to display multi purpose pop-up message dialog
    public void MessageDialog(Context context, String msg) {
        AlertDialog.Builder alertDialogBuilder = new AlertDialog.Builder(context);

        alertDialogBuilder.setMessage(msg)
                .setCancelable(false)
                .setPositiveButton(android.R.string.ok, new
                        DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialog, int which) {
                                dialog.dismiss();
                            }
                        }).create().show();
    }

}

class M2OField {
    public Integer id;
    public String value;
}`

**Comment by adadion** [comment]
I ended up with sending params one by one. And the error occured because of empty date. Now, I'll open new issue.
